export const slike = [
    {
        sifra: 1,
        naziv: 'Purle serenity',
        godinaIzrade: 2026,
        tehnika: 'mix media na medijapanu',
        sirina: 50,
        visina: 70,
        dostupnost: true,
        image: '',
    },
    {
        sifra: 2,
        naziv: 'Pinky prommise',
        godinaIzrade: 2026,
        tehnika: 'akril na platnu',
        sirina: 50,
        visina: 70,
        dostupnost: false,
        image: '',
    },
    {
        sifra: 3,
        naziv: 'Kristinina slika',
        godinaIzrade: 2026,
        tehnika: 'akril na platnu',
        sirina: 20,
        visina:30,
        dostupnost: false,
        image: '',
    },
    {
        sifra: 4,
        naziv: 'Guardian of horizonte',
        godinaIzrade: 2026,
        tehnika: 'akril na platnu',
        sirina: 70,
        visina: 100,
        dostupnost: false,
        image: '',
    },
    {
        sifra: 5,
        naziv: 'Feniks',
        godinaIzrade: 2025,
        tehnika: 'akril na platnu',
        sirina: 70,
        visina: 100,
        dostupnost: false,
        image: '',
    },
    {
        sifra: 6,
        naziv: 'Svitanje u Kopačkom Ritu',
        godinaIzrade: 2025,
        tehnika: 'akril na platnu',
        sirina: 70,
        visina: 100,
        dostupnost: false,
        image: '',
    },
    {
        sifra: 7,
        naziv: 'vile na maslačku',
        godinaIzrade: 2025,
        tehnika: 'akril na platnu',
        sirina: 70,
        visina: 50,
        dostupnost: false,
        image: '',
    }

]